Universe       = vanilla 
GetEnv         = True
Initialdir     = /home/kouseki.miyo/kagra-gif/monitor/earthquake
Notify_User    =
Notification   = Never
+Group         = "Xc"
request_memory = 4 GB

Executable = /usr/bin/python 
Error      = /home/kouseki.miyo/kagra-gif/monitor/earthquake/log/main.$(Process).err
Log        = /home/kouseki.miyo/kagra-gif/monitor/earthquake/log/main.$(Process).log
Output     = /home/kouseki.miyo/kagra-gif/monitor/earthquake/log/main.$(Process).out

RequestCpus    = 14
Arguments  = /home/kouseki.miyo/kagra-gif/monitor/earthquake/get_gwf.py
Queue