
Universe       = vanilla 
GetEnv         = True
Initialdir     = /home/kouseki.miyo/Git/kagra-gif/ugm/seismicnoise
Notification   = Never
+Group         = "Xc"
request_memory = 4 GB

#Executable = /usr/bin/python 
Executable = /home/kouseki.miyo/anaconda3/envs/miyo-py37/bin/python 
Error      = ./log/main.$(Process).err
Log        = ./log/main.$(Process).log
Output     = ./log/main.$(Process).out
