
Universe       = vanilla 
GetEnv         = True
Initialdir     = /home/kouseki.miyo/Git/kagra-gif/ugm/seismicnoise
Notification   = Never
+Group         = "Xc"
request_memory = 16 GB

Executable = /usr/bin/python 
Error      = ./log/main.$(Process).err
Log        = ./log/main.$(Process).log
Output     = ./log/main.$(Process).out

RequestCpus    = 8
Arguments  = ./main.py --start 1211817600 --end 1245372032 --nproc 8 --seis EXV --asd
Queue
