Universe       = vanilla 
GetEnv         = True
Initialdir     = /home/kouseki.miyo/kagra-gif/alcs/sensor_correction_trial
Notification   = Never
+Group         = "Xc"
request_memory = 1 GB

Executable = /usr/bin/python
Error      = ./log/main.$(Process).err
Log        = ./log/main.$(Process).log
Output     = ./log/main.$(Process).out

RequestCpus    = 1
Arguments  = ./main.py sc2_0
Queue

RequestCpus    = 1
Arguments  = ./main.py sc2_1
Queue